//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Modelo_Entidades
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class WASSTD_AuditoriaContainer : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto WASSTD_AuditoriaContainer usando la cadena de conexión encontrada en la sección 'WASSTD_AuditoriaContainer' del archivo de configuración de la aplicación.
        /// </summary>
        public WASSTD_AuditoriaContainer() : base("name=WASSTD_AuditoriaContainer", "WASSTD_AuditoriaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto WASSTD_AuditoriaContainer.
        /// </summary>
        public WASSTD_AuditoriaContainer(string connectionString) : base(connectionString, "WASSTD_AuditoriaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto WASSTD_AuditoriaContainer.
        /// </summary>
        public WASSTD_AuditoriaContainer(EntityConnection connection) : base(connection, "WASSTD_AuditoriaContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Auditoria_Log> Auditorias_Log
        {
            get
            {
                if ((_Auditorias_Log == null))
                {
                    _Auditorias_Log = base.CreateObjectSet<Auditoria_Log>("Auditorias_Log");
                }
                return _Auditorias_Log;
            }
        }
        private ObjectSet<Auditoria_Log> _Auditorias_Log;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Auditoria_Tramite> Auditorias_Tramites
        {
            get
            {
                if ((_Auditorias_Tramites == null))
                {
                    _Auditorias_Tramites = base.CreateObjectSet<Auditoria_Tramite>("Auditorias_Tramites");
                }
                return _Auditorias_Tramites;
            }
        }
        private ObjectSet<Auditoria_Tramite> _Auditorias_Tramites;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Auditoria_Detalles_Tramite> Auditoria_Detalles_Tramites
        {
            get
            {
                if ((_Auditoria_Detalles_Tramites == null))
                {
                    _Auditoria_Detalles_Tramites = base.CreateObjectSet<Auditoria_Detalles_Tramite>("Auditoria_Detalles_Tramites");
                }
                return _Auditoria_Detalles_Tramites;
            }
        }
        private ObjectSet<Auditoria_Detalles_Tramite> _Auditoria_Detalles_Tramites;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Auditorias_Log. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAuditorias_Log(Auditoria_Log auditoria_Log)
        {
            base.AddObject("Auditorias_Log", auditoria_Log);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Auditorias_Tramites. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAuditorias_Tramites(Auditoria_Tramite auditoria_Tramite)
        {
            base.AddObject("Auditorias_Tramites", auditoria_Tramite);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Auditoria_Detalles_Tramites. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAuditoria_Detalles_Tramites(Auditoria_Detalles_Tramite auditoria_Detalles_Tramite)
        {
            base.AddObject("Auditoria_Detalles_Tramites", auditoria_Detalles_Tramite);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WASSTD_Auditoria", Name="Auditoria_Detalles_Tramite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auditoria_Detalles_Tramite : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Auditoria_Detalles_Tramite.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="detalle_anterior">Valor inicial de la propiedad detalle_anterior.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="fecha_detalle_anterior">Valor inicial de la propiedad fecha_detalle_anterior.</param>
        /// <param name="accion">Valor inicial de la propiedad accion.</param>
        /// <param name="id_tramite">Valor inicial de la propiedad id_tramite.</param>
        public static Auditoria_Detalles_Tramite CreateAuditoria_Detalles_Tramite(global::System.Int32 id, global::System.String detalle_anterior, global::System.String usuario, global::System.DateTime fecha_detalle_anterior, global::System.String accion, global::System.Int32 id_tramite)
        {
            Auditoria_Detalles_Tramite auditoria_Detalles_Tramite = new Auditoria_Detalles_Tramite();
            auditoria_Detalles_Tramite.id = id;
            auditoria_Detalles_Tramite.detalle_anterior = detalle_anterior;
            auditoria_Detalles_Tramite.usuario = usuario;
            auditoria_Detalles_Tramite.fecha_detalle_anterior = fecha_detalle_anterior;
            auditoria_Detalles_Tramite.accion = accion;
            auditoria_Detalles_Tramite.id_tramite = id_tramite;
            return auditoria_Detalles_Tramite;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String detalle_anterior
        {
            get
            {
                return _detalle_anterior;
            }
            set
            {
                Ondetalle_anteriorChanging(value);
                ReportPropertyChanging("detalle_anterior");
                _detalle_anterior = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("detalle_anterior");
                Ondetalle_anteriorChanged();
            }
        }
        private global::System.String _detalle_anterior;
        partial void Ondetalle_anteriorChanging(global::System.String value);
        partial void Ondetalle_anteriorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha_detalle_anterior
        {
            get
            {
                return _fecha_detalle_anterior;
            }
            set
            {
                Onfecha_detalle_anteriorChanging(value);
                ReportPropertyChanging("fecha_detalle_anterior");
                _fecha_detalle_anterior = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha_detalle_anterior");
                Onfecha_detalle_anteriorChanged();
            }
        }
        private global::System.DateTime _fecha_detalle_anterior;
        partial void Onfecha_detalle_anteriorChanging(global::System.DateTime value);
        partial void Onfecha_detalle_anteriorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String accion
        {
            get
            {
                return _accion;
            }
            set
            {
                OnaccionChanging(value);
                ReportPropertyChanging("accion");
                _accion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("accion");
                OnaccionChanged();
            }
        }
        private global::System.String _accion;
        partial void OnaccionChanging(global::System.String value);
        partial void OnaccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tramite
        {
            get
            {
                return _id_tramite;
            }
            set
            {
                if (_id_tramite != value)
                {
                    Onid_tramiteChanging(value);
                    ReportPropertyChanging("id_tramite");
                    _id_tramite = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tramite");
                    Onid_tramiteChanged();
                }
            }
        }
        private global::System.Int32 _id_tramite;
        partial void Onid_tramiteChanging(global::System.Int32 value);
        partial void Onid_tramiteChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WASSTD_Auditoria", Name="Auditoria_Log")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auditoria_Log : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Auditoria_Log.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="accion">Valor inicial de la propiedad accion.</param>
        public static Auditoria_Log CreateAuditoria_Log(global::System.Int32 id, global::System.String usuario, global::System.DateTime fecha, global::System.String accion)
        {
            Auditoria_Log auditoria_Log = new Auditoria_Log();
            auditoria_Log.id = id;
            auditoria_Log.usuario = usuario;
            auditoria_Log.fecha = fecha;
            auditoria_Log.accion = accion;
            return auditoria_Log;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String accion
        {
            get
            {
                return _accion;
            }
            set
            {
                OnaccionChanging(value);
                ReportPropertyChanging("accion");
                _accion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("accion");
                OnaccionChanged();
            }
        }
        private global::System.String _accion;
        partial void OnaccionChanging(global::System.String value);
        partial void OnaccionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WASSTD_Auditoria", Name="Auditoria_Tramite")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Auditoria_Tramite : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Auditoria_Tramite.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="tipo_Tramite_id">Valor inicial de la propiedad Tipo_Tramite_id.</param>
        /// <param name="estado_id">Valor inicial de la propiedad Estado_id.</param>
        /// <param name="persona_DNI">Valor inicial de la propiedad Persona_DNI.</param>
        /// <param name="accion">Valor inicial de la propiedad accion.</param>
        /// <param name="usuario">Valor inicial de la propiedad usuario.</param>
        /// <param name="id_tramite">Valor inicial de la propiedad id_tramite.</param>
        public static Auditoria_Tramite CreateAuditoria_Tramite(global::System.Int32 id, global::System.Boolean tipo_Tramite_id, global::System.String estado_id, global::System.Int32 persona_DNI, global::System.String accion, global::System.String usuario, global::System.Int32 id_tramite)
        {
            Auditoria_Tramite auditoria_Tramite = new Auditoria_Tramite();
            auditoria_Tramite.id = id;
            auditoria_Tramite.Tipo_Tramite_id = tipo_Tramite_id;
            auditoria_Tramite.Estado_id = estado_id;
            auditoria_Tramite.Persona_DNI = persona_DNI;
            auditoria_Tramite.accion = accion;
            auditoria_Tramite.usuario = usuario;
            auditoria_Tramite.id_tramite = id_tramite;
            return auditoria_Tramite;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Tipo_Tramite_id
        {
            get
            {
                return _Tipo_Tramite_id;
            }
            set
            {
                OnTipo_Tramite_idChanging(value);
                ReportPropertyChanging("Tipo_Tramite_id");
                _Tipo_Tramite_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tipo_Tramite_id");
                OnTipo_Tramite_idChanged();
            }
        }
        private global::System.Boolean _Tipo_Tramite_id;
        partial void OnTipo_Tramite_idChanging(global::System.Boolean value);
        partial void OnTipo_Tramite_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Estado_id
        {
            get
            {
                return _Estado_id;
            }
            set
            {
                OnEstado_idChanging(value);
                ReportPropertyChanging("Estado_id");
                _Estado_id = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Estado_id");
                OnEstado_idChanged();
            }
        }
        private global::System.String _Estado_id;
        partial void OnEstado_idChanging(global::System.String value);
        partial void OnEstado_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Persona_DNI
        {
            get
            {
                return _Persona_DNI;
            }
            set
            {
                OnPersona_DNIChanging(value);
                ReportPropertyChanging("Persona_DNI");
                _Persona_DNI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Persona_DNI");
                OnPersona_DNIChanged();
            }
        }
        private global::System.Int32 _Persona_DNI;
        partial void OnPersona_DNIChanging(global::System.Int32 value);
        partial void OnPersona_DNIChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String accion
        {
            get
            {
                return _accion;
            }
            set
            {
                OnaccionChanging(value);
                ReportPropertyChanging("accion");
                _accion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("accion");
                OnaccionChanged();
            }
        }
        private global::System.String _accion;
        partial void OnaccionChanging(global::System.String value);
        partial void OnaccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tramite
        {
            get
            {
                return _id_tramite;
            }
            set
            {
                if (_id_tramite != value)
                {
                    Onid_tramiteChanging(value);
                    ReportPropertyChanging("id_tramite");
                    _id_tramite = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tramite");
                    Onid_tramiteChanged();
                }
            }
        }
        private global::System.Int32 _id_tramite;
        partial void Onid_tramiteChanging(global::System.Int32 value);
        partial void Onid_tramiteChanged();

        #endregion

    
    }

    #endregion

    
}
